### ISSUE TITLE
插件内报错Cannot read property 'method'

### ISSUE THREAD

**Issue by clevok** [Tencent/Face2FaceTranslator#27]
刚上线使用语言识别的插件
就频繁告警

```js
Cannot read property 'method' of null;at socketTask.onopen callback function
TypeError: Cannot read property 'method' of null
at Object._buildWebsocketFrame (https://usr/app-service.js:1086:19965)
at Object.internalSend (https://usr/app-service.js:1086:20603)
at Function.<anonymous> (https://usr/app-service.js:1086:21402)
at i.emit (https://lib/WASubContext.js:1:371583)
at https://lib/WASubContext.js:1:699502
at https://lib/WASubContext.js:1:381835
```

排查是插件内导致，主要是socket方法原小程序内没有使用过，且这个错误发现是新版本才有的

**Comment by clevok** [comment]
客户端版本 7.0.4
