### ISSUE TITLE
插件内 socket部分处理不当呀，一直在报错

### ISSUE THREAD

**Issue by clevok** [Tencent/Face2FaceTranslator#29]
```js
Cannot read property 'close' of null;at api connectSocket fail callback function
TypeError: Cannot read property 'close' of null
at Object.closeWebsocket (https://usr/app-service.js:1086:23027)
at Object._reconnectWebosocket (https://usr/app-service.js:1086:19527)
at Function.fail (https://usr/app-service.js:1086:23427)
```

猜测是
```js 
wx.connectSocket({
    fail() {
// 这处代码是不是有问题呀， 比如某个变量是null，却又 取了 null.close 属性
    }
})
```

---

还有一个地方错误
```js
Cannot read property 'method' of null;at socketTask.onopen callback function
TypeError: Cannot read property 'method' of null
at Object._buildWebsocketFrame (https://usr/app-service.js:1086:19965)
at Object.internalSend (https://usr/app-service.js:1086:20603)
at Function.<anonymous> (https://usr/app-service.js:1086:21402)
```
猜测
```js
wx.onSocketOpen(()=>{
// 是不是一样的问题， 取了 null.method
})

```
相同位置还有一个报错
```js
null is not an object (evaluating 't.method');at socketTask.onopen callback function
_buildWebsocketFrame@https://usr/app-service.js:1086:19964
internalSend@https://usr/app-service.js:1086:20623
https://usr/app-service.js:1086:21414
https://lib/WAService.js:1:101985
emit@https://lib/WAService.js:1:244006
https://lib/WAService.js:1:532917
https://lib/WAService.js:1:254330
S@https://lib/WAService.js:1:1769
```

很着急，一直在报警

**Comment by clevok** [comment]
能否修复给个答复吧，一直在找解决方案

**Comment by XT1024** [comment]
你好，昨天已经邮件联系你，麻烦查看下？

**Comment by clevok** [comment]
> 你好，昨天已经邮件联系你，麻烦查看下？

好的抱歉，看到了，没有留意邮箱

**Comment by clevok** [comment]
你好，今天在排查数据的时候，发现，这个报错在微信 7.0.5 中十分密集
因为目前早上7点钟开始告警，但7点实时访问次数已经过万了很难排查到具体是哪些机型报错


想请问一下, 目前有什么办法能够减少此类错误吗

Sheet1
                                          客户端版本版本错误次数 总错误次数 次数占比 　 
6.7.3450750.08%Cannot read property 'method' of null;at socketTask.onopen callback function
 
7.0.0650750.12%Cannot read property 'method' of null;at socketTask.onopen callback function
TypeError: Cannot read property 'method' of null
at Object._buildWebsocketFrame (https://usr/app-service.js:1086:19965)
at Object.internalSend (https://usr/app-service.js:1086:20603)
at Function.<anonymous> (https://usr/app-service.js:1086:21402)
at Rt.emit (https://lib/WASubContext.js:1:286667)
at https://lib/WASubContext.js:1:460525
at https://lib/WASubContext.js:1:243921 
7.0.11244.17% null is not an object (evaluating 't.method');at socketTask.onopen callback function
_buildWebsocketFrame@https://usr/app-service.js:1086:19964
internalSend@https://usr/app-service.js:1086:20623
https://usr/app-service.js:1086:21414
https://lib/WAService.js:1:101845
emit@https://lib/WAService.js:1:314666
https://lib/WAService.js:1:487872
https://lib/WAService.js:1:271977
S@https://lib/WAService.js:1:1762 
7.0.55590714778.21%Cannot read property 'method' of null;at socketTask.onopen callback function
TypeError: Cannot read property 'method' of null
at Object._buildWebsocketFrame (https://usr/app-service.js:1086:19965)
at Object.internalSend (https://usr/app-service.js:1086:20603)
at Function.<anonymous> (https://usr/app-service.js:1086:21402) 
7.0.617630.13% Cannot read property 'method' of null;at socketTask.onopen callback function
TypeError: Cannot read property 'method' of null
at Object._buildWebsocketFrame (https://usr/app-service.js:1086:19965)
at Object.internalSend (https://usr/app-service.js:1086:20603)
at Function.<anonymous> (https://usr/app-service.js:1086:21402)













------------------ 原始邮件 ------------------
发件人: "lethexie"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 上午10:28
收件人: "Tencent/Face2FaceTranslator"<Face2FaceTranslator@noreply.github.com>;
抄送: "王阿龙"<1029794653@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/Face2FaceTranslator] 插件内 socket部分处理不当呀，一直在报错 (#29)




你好，昨天已经邮件联系你，麻烦查看下？
